version: "3.8"

services:
  loki:
    image: grafana/loki:3.2.0
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    networks:
      - platform_net
    deploy:
      replicas: 1

  promtail:
    image: grafana/promtail:3.2.0
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/swarm/promtail/config.yml:/etc/promtail/config.yml:ro
    networks:
      - platform_net
    deploy:
      mode: global

networks:
  platform_net:
    external: true
