version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.55.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - /srv/swarm/prometheus:/prometheus
      - /srv/swarm/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - platform_net
    deploy:
      replicas: 1

  grafana:
    image: grafana/grafana-oss:11.2.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "Grafana@Admin1!"
    volumes:
      - /srv/swarm/grafana:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - platform_net
    deploy:
      replicas: 1

networks:
  platform_net:
    external: true
