version: "3.8"

services:
  trivy-server:
    image: aquasec/trivy:0.57.0
    command: ["server", "--listen", "0.0.0.0:4954"]
    ports:
      - "4954:4954"
    volumes:
      - /srv/swarm/trivy:/root/.cache/trivy
    networks:
      - platform_net
    deploy:
      replicas: 1

networks:
  platform_net:
    external: true
